version: "3.9"

services:
  prisma_pscale_test:
    image: mysql:8.0.33
    container_name: prisma_pscale_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    ports:
      - "33061:3306"
    volumes:
      - prisma_pscale_test_data:/var/lib/mysql

volumes:
  prisma_pscale_test_data:
