import type { NextPage } from 'next'
import { GetServerSidePropsContext } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { getToken } from 'next-auth/jwt'
import { signOut } from 'next-auth/react'
import { Route } from 'constants/common/routes'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>appName</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Home</p>
      <Link passHref href={Route.Admin}>
        <button>Admin</button>
      </Link>
      <Link passHref href={Route.Member}>
        <button>Member</button>
      </Link>
      <button
        onClick={() => {
          void (() => signOut())()
        }}
      >
        logOut logOut
      </button>
    </div>
  )
}

export const getServerSideProps = async (context: GetServerSidePropsContext) => {
  const token = await getToken({ req: context.req })
  if (!token) {
    return {
      redirect: {
        destination: Route.SignIn,
        permanent: false,
      },
    }
  }
}

export default Home
