import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { signOut } from 'next-auth/react'
import { Route } from 'constants/common/routes'
import { useHelloQuery } from 'generated/graphqlClient'

const Home: NextPage = () => {
  const { data } = useHelloQuery({ variables: { message: 'Hello message' } })

  console.log('data', data)

  return (
    <div>
      <Head>
        <title>appName</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Home</p>
      <Link passHref href={Route.Admin}>
        <button>Admin</button>
      </Link>
      <Link passHref href={Route.Member}>
        <button>Member</button>
      </Link>
      <button
        onClick={() => {
          void (() => signOut())()
        }}
      >
        logOut logOut
      </button>
    </div>
  )
}

export default Home
