name: Auto Author Assign

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    name: Auto Author Assign
    steps:
      - name: assign-author
        uses: toshimaru/auto-author-assign@v1.4.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
